---
- name: Déploiement d'un site avec Apache
  hosts: linux
  become: yes
  handlers:
    - name: "Rechargement du Firewall"
      service:
        name: firewalld
        state: reloaded
  tasks:
    - name: Installation d'Apache pour Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"
      
    - name: Installation d'Apache pour CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Déploiement index.html
      template:
        src: ./s8_index.j2
        dest: /var/www/html/index.html

    - name: Restart service Apache pour Ubuntu
      service:
        name: apache2
        state: reloaded
      when: ansible_distribution == "Ubuntu"

    - name: Restart service Apache pour CentOS
      service:
        name: httpd
        state: reloaded
      when: ansible_distribution == "CentOS"

    - name: Autorisation du service http sur le Firewall
      firewalld:
        port: 80/tcp
        state: enabled
        permanent: yes
      register: res_fw
      notify: ["Rechargement du Firewall"]

    - name: Debug Ouverture Firewall
      debug:
        msg: "{{res_fw}}"
...
